Updated login test feature
bibekthapa619/jobtriage pull request #1
Opened 2020-05-12 06:11 UTC by bibekthapa619

# Pull Request Template

## Description

There was a test for login. Feature file was updated.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-05-12 07:05 UTC, kiranparajuli589 commented on frontend/tests/acceptance/features/webUILogin/login.feature
So that ...

2020-05-12 07:11 UTC, Talank reviewed
fix the spacings

2020-05-12 07:11 UTC, Talank commented on frontend/tests/acceptance/features/webUILogin/login.feature
> +  Scenario: login  with blank email
```suggestion
  Scenario: login with blank email
```

2020-05-12 07:11 UTC, Talank commented on frontend/tests/acceptance/features/webUILogin/login.feature
> +      | password | passwo       |
fix the spacing

2020-05-21 04:11 UTC, Talank reviewed
Fix some minor issues

2020-05-21 04:11 UTC, Talank commented on frontend/tests/acceptance/step_definitions/loginContext.js
> +  "the user signs up with name {string}, email {string} password {string} and confirmation password {string} using the webUI",
fix the space. I don't think any change is required here

2020-05-21 04:11 UTC, Talank commented on frontend/tests/acceptance/step_definitions/loginContext.js
> +  (email, password) => {
these 3 lines should be 1

2020-05-21 04:11 UTC, Talank commented on frontend/tests/acceptance/step_definitions/loginContext.js
> +});
this is same as above!
```
Then("user should be redirected to the dashboard page", () =>
  I.seeElement(dashboard.dashboardContainer)
);
```
This step is repeated

2020-05-21 04:11 UTC, Talank commented on frontend/tests/acceptance/features/webUILogin/login.feature
> +          Then the user should stay on the same page
be more specific here

2020-05-21 05:50 UTC, kiranparajuli589 commented
**NOTE** :Resolve the review conversation after the changes has been made!

2020-05-21 06:01 UTC, Talank commented on frontend/tests/acceptance/step_definitions/loginContext.js
> +const signupPage = require("../pages/signupPage");
I don't think these single quotes need to be changed to double quotes

2020-05-21 06:01 UTC, Talank commented on frontend/tests/acceptance/step_definitions/loginContext.js
> +Given("the user has browsed to the homepage", () => I.amOnPage("/"));
Same here. Don't need to change the quotes

2020-05-27 05:04 UTC, kiranparajuli589 commented on frontend/tests/acceptance/step_definitions/loginContext.js
> +    globals.users.push(email);
```suggestion
    globals.users.push({"email": email, "password": password});
```

2020-06-01 04:50 UTC, Talank commented on .travis.yml
> +#   - docker
get rid of this comment.

2020-06-01 04:50 UTC, Talank commented on frontend/tests/acceptance/pages/loginPage.js
> +      '//label[contains(text(),"Password")]/parent::div/div/input[contains(@class, "MuiInputBase-input")]',
```suggestion
    email: '//label[contains(text(),"Email")]/parent::div/div/input[contains(@class, "MuiInputBase-input")]',
    password: '//label[contains(text(),"Password")]/parent::div/div/input[contains(@class, "MuiInputBase-input")]',
```

2020-06-01 04:50 UTC, Talank commented on frontend/tests/acceptance/pages/signupPage.js
> +      '//label[contains(text(),"Name")]/parent::div/div/input[contains(@class, "MuiInputBase-input")]',
put name and XPath in the same line

2020-06-01 04:50 UTC, Talank commented on frontend/tests/acceptance/pages/signupPage.js
> +      '//label[contains(text(),"Confirm password")]/parent::div/div/input[contains(@class, "MuiInputBase-input")]',
same here

2020-06-01 04:50 UTC, Talank commented on frontend/tests/acceptance/step_definitions/loginContext.js
> +  console.log(globals.users);
remove this console.log()

2020-06-01 05:10 UTC, kiranparajuli589 requested changes

2020-06-01 05:10 UTC, kiranparajuli589 commented on frontend/tests/acceptance/helpers/api/user.js
> +      //  Status: ${error.response.statusText}`);
console logging the caught error would be nice here or throw Error

2020-06-01 05:10 UTC, kiranparajuli589 commented on frontend/tests/acceptance/pages/signupPage.js
> +      '//label[contains(text(),"Email")]/parent::div/div/input[contains(@class, "MuiInputBase-input")]',
```suggestion
      '//label[contains(text(),"%s")]/parent::div//input[contains(@class, "MuiInputBase-input")]',
```
and use `util.format()` where you need the xpath

2020-06-01 05:10 UTC, kiranparajuli589 commented on frontend/tests/acceptance/features/webUISignup/signup.feature
> +    Then the user should be redirected to the dashboard page
Add some scenarios to explain invalid sigup concept!

2020-06-19 07:59 UTC, Talank approved these changes

2020-06-19 16:31 UTC, closed without merging